# Generated by Django 2.1.3 on 2021-06-15 05:03

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sheets', jsonfield.fields.JSONField(null=True)),
                ('headers', jsonfield.fields.JSONField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sheets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('program', models.CharField(max_length=100)),
                ('Time_cycle', jsonfield.fields.JSONField(null=True)),
                ('Sensor_1', jsonfield.fields.JSONField(null=True)),
                ('Sensor_2', jsonfield.fields.JSONField(null=True)),
                ('Sensor_3', jsonfield.fields.JSONField(null=True)),
                ('Sensor_4', jsonfield.fields.JSONField(null=True)),
                ('Sensor_5', jsonfield.fields.JSONField(null=True)),
                ('Sensor_6', jsonfield.fields.JSONField(null=True)),
                ('Sensor_7', jsonfield.fields.JSONField(null=True)),
                ('Sensor_8', jsonfield.fields.JSONField(null=True)),
                ('Sensor_9', jsonfield.fields.JSONField(null=True)),
                ('Sensor_10', jsonfield.fields.JSONField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series', to='projects.Series')),
            ],
        ),
    ]
